// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import RoutesController from "./routes_controller"
application.register("routes", RoutesController)

import DirectionsController from "./directions_controller"
application.register("directions", DirectionsController)

import WaypointsController from "./waypoints_controller"
application.register("waypoints", WaypointsController)

import OverpassMapController from "./overpass_map_controller"
application.register("overpass-map", OverpassMapController)

import WaypointNotesController from "./waypoint_notes_controller"
application.register("waypoint-notes", WaypointNotesController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)